### PR TITLE
Update pathfinder2e.mapping

### PR DESCRIPTION
**Pull request by korstefan14**
This changes all appearances of i.data.featType.value to i.data.category to make it work with PF2e Version 4.10.4

### CODE REVIEW

**Comment by korstefan14** [comment]
This Should resolve Issue #77 and possibly also #76

**Comment by Picos** [comment]
Hello, you need to change also the value of type :
'ancestryfeature' become 'ancestry'
'classfeature' become 'class'

**Comment by arcanistzed** [comment]
@korstefan14 can this be closed in favor of #80?

**Comment by korstefan14** [comment]
> @korstefan14 can this be closed in favor of #80?

If #80 works in the current pathfinder version, then go ahead and close this.

**Pull request closed without merging**
