### PR TITLE
Updated mapping for upcoming charakterbogen_ataendler_v2.8.1.pdf

### PR DESCRIPTION
**Pull request by manolitto**
A new pdf version 2.8.1 will soon be released - this mapping already takes the upcoming changes into account

### CODE REVIEW

**Comment by arcanistzed** [comment]
Could you notify me when this new version of the PDF is released? Thanks

**Comment by manolitto** [comment]
> Could you notify me when this new version of the PDF is released? Thanks

Sure, as soon as 2.8.1 is released and available I will create a PR that has the correct referencing link inside the mapping file and in the README.

**Comment by arcanistzed** [comment]
@manolitto What's the status on this?

**Comment by manolitto** [comment]
ok, I got green light and I updated the link and also updated the mapping file to the latest changes
please go ahead and pull
thanks

**Review by arcanistzed — APPROVED** [review]

**Pull request merged**
