### PR TITLE
Update to V10 mappings

### PR DESCRIPTION
**Pull request by trevorschadt**
With the massive changes in data structures released as part of V10, the previous version of this mapping no longer worked. This change updates the mappings to reflect those data structure changes and restore functionality.

Please note that Power Shifts will not be populated onto the sheet in the Power Shifts section, as this was getting way too finicky. They are instead added to the special abilities area, and players/GMs who wish to do so can easily translate them over.

### CODE REVIEW

**Comment by gioppoluca** [comment]
are we sure that the old mapping is not needed for previoud foundry version? I'd not like to break things for V9, let me know if you prefer to add a new mapping for v10 leaving the old onw for v9 (maybe renaming it for clarity). Thanks

**Comment by trevorschadt** [comment]
> are we sure that the old mapping is not needed for previoud foundry version? I'd not like to break things for V9, let me know if you prefer to add a new mapping for v10 leaving the old onw for v9 (maybe renaming it for clarity). Thanks

We are not sure of that, no. If you'd prefer to keep backward compatibility, I have no issue with renaming the file. I'd be curious to see user base statistics on how many people are still using V9 or earlier.

Please let me know your preference, and if I need to do something to make it happen, I'm certainly happy to do so.

**Comment by gioppoluca** [comment]
If you manage to rename the updated file so we can keep the old one for users that still use foundry V9.
Thanks

**Comment by trevorschadt** [comment]
I have closed this pull request and added a new one that simply adds the new file.

**Pull request closed without merging**
