### PR TITLE
Fixed for v11 and closes #10

### PR DESCRIPTION
**Pull request by gioppoluca**
This makes the module work in V11 and fixes incompatibility with latest DND5e

### CODE REVIEW

**Comment by gioppoluca** [comment]
I fixed the traits.toolProf in a way that leave it compatible with older DND5e versions, but the most recent has moved that object here: system.tools
So either a more complex management or a breaking change to go with only latest version.  Up to you ... apart that all should work

**Comment by gioppoluca** [comment]
wrong # ... it closes #81 sorry

**Comment by ChrisAndelin** [comment]
I tested this and it didn't throw any errors.
image

**Comment by naesean** [comment]
@gioppoluca any chance this can get merged and released? Would love to use this for my v11 games. Thanks so much!

**Comment by gioppoluca** [comment]
I added the german fixes and fixed the dnd5e mapping
Also added the initial mapping for the spellbook template

**Review by arcanistzed — COMMENTED** [review]
What is the PDF? Do you have license to use it and the ODT here? If so, re you releasing it under this repository's MIT or do you need to include another license file?

**Review by gioppoluca — COMMENTED** [review]
This PR fixes things for V11

**Review by arcanistzed — APPROVED** [review]

**Comment by naesean** [comment]
Looking forward to seeing this released!

**Pull request merged**
