### PR TITLE
SWADE support

### PR DESCRIPTION
**Pull request by SalmonRain**
Added the SWADE mapping file I've been using.
Maps to the nodice sheet available on https://peginc.com/store/savage-worlds-character-sheet-pdf-swade/.
Cheers.

### CODE REVIEW

**Comment by arcanistzed** [comment]
Nice. Thank you!
I like what you did with the helper functions :smile:
Do you want to also add metadata to https://github.com/arcanistzed/pdf-sheet/blob/main/languages/en.json so that the button automatically directs users to the correct PDF?

**Comment by SalmonRain** [comment]
I would but PEG only provides that link to their store. No direct links to pdf's.
I'd host it myself but I have no idea if I can do that legally. I'm asking around about it for now.

**Comment by arcanistzed** [comment]
@SalmonRain There's no need for it to be a direct link. The module will just open the store when you click on the button instead:

```json
"dnd5e": {
      "label": "PDF for SWADE",
      "title": "View the the official character sheet PDF for SWADE in the PEG store",
      "url": "https://peginc.com/store/savage-worlds-character-sheet-pdf-swade/"
},
```

**Comment by SalmonRain** [comment]
@arcanistzed Very well, it's been added :)

**Review by arcanistzed — APPROVED** [review]

**Pull request merged**
